### ISSUE TITLE
Decoding "\\%"

### ISSUE THREAD

**Issue by tschantzmc** [mcmtroffaes/latexcodec#72]
The LaTeX `\\%` should be decoded as `u'\n'`, or at least as `u'\\\\'`.  Instead, it produces an error.

The following prgram illistrates the issue for Python 3.6.5 and latexcodec 1.0.7:
```python3
#! /usr/bin/env python3

import codecs
import latexcodec

print(codecs.decode(u'\\\\%', 'ulatex'))
```
It produces the output:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/latexcodec/lexer.py", line 389, in decode
    return u''.join(self.get_unicode_tokens(bytes_, final=final))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/latexcodec/codec.py", line 788, in get_unicode_tokens
    for token in self.get_tokens(bytes_, final=final):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/latexcodec/lexer.py", line 324, in get_tokens
    "unknown token {0!r}".format(token.text))
UnicodeDecodeError: 'latex' codec can't decode byte 0x25 in position 2: unknown token '%'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test7.py", line 6, in <module>
    print(codecs.decode(u'\\\\%', 'ulatex'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/latexcodec/codec.py", line 836, in decode
    decoder.decode(bytes_, final=True),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/latexcodec/lexer.py", line 393, in decode
    raise ValueError(e)
ValueError: 'latex' codec can't decode byte 0x25 in position 2: unknown token '%'
```

**Comment by mcmtroffaes** [comment]
Yes, you found an interesting corner case that the lexer currently cannot handle. Congratulations! :-)

I believe that the negative lookbehind in the comment lexer rule ``r'(?<![\\])%[^\n]*')`` (see https://github.com/mcmtroffaes/latexcodec/blob/develop/latexcodec/lexer.py#L148 ) needs to be changed to match only an odd number of backslashes preceding it.

**Comment by mcmtroffaes** [comment]
This should now be fixed (will pull into develop momentarily).
