### ISSUE TITLE
Encoding \u2113

### ISSUE THREAD

**Issue by jeffrey-hokanson** [mcmtroffaes/latexcodec#89]
I am running betterbib which calls this library.  I think I am running into an issue with this library encoding ℓ.  The error I get is:

```
Traceback (most recent call last):
  File "/Users/jeffreyh/Library/Python/3.9/lib/python/site-packages/latexcodec/codec.py", line 745, in _get_latex_chars_tokens_from_char
    return self.table.latex_map[c]
KeyError: 'ℓ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jeffreyh/Library/Python/3.9/bin/betterbib", line 8, in <module>
    sys.exit(main())
  File "/Users/jeffreyh/Library/Python/3.9/lib/python/site-packages/betterbib/cli/full.py", line 33, in main
    tools.write(d, args.outfile, args.delimeter_type, tab_indent=args.tab_indent)
  File "/Users/jeffreyh/Library/Python/3.9/lib/python/site-packages/betterbib/tools.py", line 403, in write
    [
  File "/Users/jeffreyh/Library/Python/3.9/lib/python/site-packages/betterbib/tools.py", line 404, in <listcomp>
    pybtex_to_bibtex_string(
  File "/Users/jeffreyh/Library/Python/3.9/lib/python/site-packages/betterbib/tools.py", line 229, in pybtex_to_bibtex_string
    value = codecs.encode(value, "ulatex")
  File "/Users/jeffreyh/Library/Python/3.9/lib/python/site-packages/latexcodec/codec.py", line 854, in encode
    encoder.encode(unicode_, final=True),
  File "/Users/jeffreyh/Library/Python/3.9/lib/python/site-packages/latexcodec/lexer.py", line 461, in encode
    chars = u''.join(self.get_latex_chars(unicode_, final=final))
  File "/Users/jeffreyh/Library/Python/3.9/lib/python/site-packages/latexcodec/codec.py", line 778, in get_latex_chars
    bytes_, tokens = self._get_latex_chars_tokens_from_char(c)
  File "/Users/jeffreyh/Library/Python/3.9/lib/python/site-packages/latexcodec/codec.py", line 749, in _get_latex_chars_tokens_from_char
    raise UnicodeEncodeError(
UnicodeEncodeError: 'latex' codec can't encode character '\u2113' in position 0: don't know how to translate 'ℓ' into latex
```

**Comment by mcmtroffaes** [comment]
Thanks for reporting. Would $\ell$ be a good match this?

**Comment by jeffrey-hokanson** [comment]
I think that would be perfect!  Thanks!

**Comment by mcmtroffaes** [comment]
Great! This is now fixed in develop.
